### ISSUE TITLE
Add Select/Option HTML tag functionality

### ISSUE THREAD

**Issue by danielgasparpereira** [Mazeakin/jquery-bootstrap-autofill#3]
Hi again.

It would be nice if, in addition to using the `<UL> <LI>` html tag for dropdown list, it would be possible to use the `<SELECT> <OPTION> `html tag where the value in option is the value in returned json data.
Do you think it would be possible?

**Thank you.**

**Comment by Gataquadrada** [comment]
The goal of this plugin is to be an autocomplete for frequently used words and terms you otherwise would have to type (_eg: linking users to a record_).

The main goal of the `<select>` tag is to [phrase content](https://html.spec.whatwg.org/multipage/form-elements.html#the-select-element). As in, insert something into a context.

For the use you are looking for, you will find solutions like [Select2](https://select2.org).
